import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <main className={""}>
      <Head>
        <title>جایی برای نوشتن</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./virgol.png" />
      </Head>
      <h1 className="text-3xl font-bold  text-red-800 underline">
        Hello world!
      </h1>
    </main>
  );
};

export default Home;
